replicaCount: 1

image:
  repository: dmvorona1nure/shop
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: ""
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: localhost
      paths:
        - path: /user(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: shop
              port:
                number: 8080
        - path: /products(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: shop
              port:
                number: 8080
        - path: /order(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: shop
              port:
                number: 8080
        - path: /cart(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: shop
              port:
                number: 8080
  tls:
    - hosts:
        - localhost
      secretName: shop-tls

resources: {}

livenessProbe:
  httpGet:
    path: /healthz
    port: http
readinessProbe:
  httpGet:
    path: /healthz
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []
