replicaCount: 1

image:
  repository: monolith-shop
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}


service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: todo
      paths:
        - path: /user(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: todo
              port:
                number: 80
        - path: /products(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: todo
              port:
                number: 80
        - path: /order(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: todo
              port:
                number: 80
        - path: /cart(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: todo
              port:
                number: 80
  tls:
    - hosts:
        - todo
      secretName: shop-tls

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

