apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/argocd
  - ../../base/cert-manager
  - ../../base/monitoring
patches:
  - target:
      kind: Application
      name: shop
    path: patch-shop.yaml
