deploy:
  monolith: true
  microservices: false

dbSecretName: sql-connection

monolith:
  name: monolith-shop
  image:
    repository: dmvoronashop.azurecr.io/monolith-shop
    tag: latest
    pullPolicy: Always
  service:
    port: 8080
  replicaCount: 1

microservices:
  product:
    enabled: true
    name: product-service
    image:
      repository: dmytrovorona1nure/products
      tag: latest
      pullPolicy: Always
    service:
      port: 8081
    replicaCount: 1
  user:
    enabled: true
    name: user-service
    image:
      repository: dmytrovorona1nure/users
      tag: latest
      pullPolicy: Always
    service:
      port: 8082
    replicaCount: 1
  cart:
    enabled: true
    name: cart-service
    image:
      repository: dmytrovorona1nure/carts
      tag: latest
      pullPolicy: Always
    service:
      port: 8083
    replicaCount: 1
  order:
    enabled: true
    name: order-service
    image:
      repository: dmytrovorona1nure/orders
      tag: latest
      pullPolicy: Always
    service:
      port: 8084
    replicaCount: 1

imagePullSecrets: []

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: shop.dmvorona.org
      paths:
        - path: /products(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: product-service
              port:
                number: 8081
        - path: /users(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: user-service
              port:
                number: 8082
        - path: /carts(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: shop
              port:
                number: 8083
        - path: /orders(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: shop
              port:
                number: 8084
  tls:
    - hosts:
        - shop.dmvorona.org
      secretName: shop-tls

resources: {}

livenessProbe:
  httpGet:
    path: /healthz
    port: http
readinessProbe:
  httpGet:
    path: /healthz
    port: http

autoscaling:
  hpa:
    enabled: false
    monolith:
      minReplicas: 1
      maxReplicas: 15
      targetCPUUtilizationPercentage: 80
    services:
      - name: product
        minReplicas: 1
        maxReplicas: 10
        targetCPUUtilizationPercentage: 80
      - name: user
        minReplicas: 1
        maxReplicas: 10
        targetCPUUtilizationPercentage: 70
      - name: cart
        minReplicas: 1
        maxReplicas: 10
        targetCPUUtilizationPercentage: 75
      - name: order
        minReplicas: 1
        maxReplicas: 10
        targetCPUUtilizationPercentage: 65
  vpa:
    enabled: false
    monolith:
      maxAllowed:
        cpu: 800m
        memory: 1600Mi
    services:
      - name: product
        maxAllowed:
          cpu: 400m
          memory: 800Mi
        controlledResources: [ "cpu", "memory" ]
      - name: user
        maxAllowed:
          cpu: 400m
          memory: 800Mi
        controlledResources: [ "cpu", "memory" ]
      - name: cart
        maxAllowed:
          cpu: 400m
          memory: 800Mi
        controlledResources: [ "cpu", "memory" ]
      - name: order
        maxAllowed:
          cpu: 400m
          memory: 800Mi
        controlledResources: [ "cpu", "memory" ]


volumes: []

volumeMounts: []
