{{- if .Values.autoscaling.hpa.enabled }}

{{- /* HPA for microservices */}}
{{- if .Values.deploy.microservices }}
{{- range .Values.autoscaling.hpa.services }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .name }}-hpa
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ .name }}
    {{- include "shop.labels" $ | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .name }}-service
  minReplicas: {{ .minReplicas }}
  maxReplicas: {{ .maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .targetCPUUtilizationPercentage }}
{{- end }}
{{- end }}

{{- /* HPA for monolith */}}
{{- if .Values.deploy.monolith }}
{{- with .Values.autoscaling.hpa.monolith }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: monolith-shop-hpa
  namespace: {{ $.Release.Namespace }}
  labels:
    app: monolith-shop
    {{- include "shop.labels" $ | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: monolith-shop
  minReplicas: {{ .minReplicas }}
  maxReplicas: {{ .maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .targetCPUUtilizationPercentage }}
{{- end }}
{{- end }}

{{- end }}
